baseURL = "http://anotiontoponder.org/"
languageCode    = "en-us"
theme           = "casper-two"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "A Notion to Ponder"
  subtitle    = "where thoughts meet the world"
  copyright   = "© 2020"

  cover       = "images/purple-lake.jpg"
  description = "A Notion To Ponder"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = ""
  githubName = "abwasker"
  linkedinName = "anoshwasker"
  mediumName = ""
  vscoName = "zadaddiya"

  logo = ""
  orgName = "AW"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  showSupport = false

  author = "Anosh Wasker"
  authorAvatar = "images/author-min.png"
  authorLocation = "Chicago, IL"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Physicist| Photographer | Teacher | Philosophy enthusiast"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

# [permalinks]
  #post = "/post/:slug/"
  #poetry = "poetry/:section"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Poetry"
  url = "/tags/poetry/"
  weight = 100
  
[[menu.main]]
  name = "Photography"
  url = "https://vsco.co/zadaddiya/gallery/"
  weight = 95

[[menu.section]]
  identifier = "section"
  title = "Section"
  name = "roller"
  url = "/poetry/"

  [[menu.main]]
    identifier = "post"
    name = "Writings"
    title = "Writings"
    url = "/post/"
    weight = -110